### ISSUE TITLE
All-sigs meeting for October 31 (tenative)

### ISSUE THREAD

**Issue by nick-l-o3de** [o3de/tsc#101]
Tenative - Nick L will be out, so `geds-dm` (discord) may officiate.

**Comment by lumberyard-employee-dm** [comment]
SIG-Core Update: 
### Roadmap
* Work on the Quality and Scalability Framework is paused, but will continue soon https://github.com/o3de/sig-core/issues/57

### New RFCs
* RFC to discuss ideas on improving first time Asset Processor experience for a new project has been published: https://github.com/o3de/sig-core/issues/59

**Comment by Naomi-Wash** [comment]
Meeting Recording: https://drive.google.com/file/d/1LnAy_fuB7W0a2OD9gE14MT8HRhjoUBPn/view?usp=sharing
