### ISSUE TITLE
All sigs check-in and roadmap for end of November

### ISSUE THREAD

**Issue by nick-l-o3de** [o3de/tsc#104]
The meeting is scheduled for November 28, 8am PST on the discord in the TAC/TSC channel.

This is your opportunity as SIG members, community members, or SIG chairs/co-chairs to disseminate information about what your SIG might be up to, and what you feel other SIGs and community members need to know about.  
It is also an opportunity to note roadmap items.  Please consider adding a link to your SIGs roadmap board.

**Comment by lumberyard-employee-dm** [comment]
SIG-Core Roadmap: https://github.com/orgs/o3de/projects/31

Updates:
* https://github.com/o3de/o3de/pull/17032 - Added changes to allow Tool applications to run in Release configurations(Editor, AP, AssetBundler)
* https://github.com/o3de/o3de/pull/17059 - Implemented changes to make renaming Core engine Gems easier.

@nick-l-o3de Script Only PR is ready for AR https://github.com/o3de/o3de/pull/16903
