### ISSUE TITLE
TSC Agenda - June 25, 2024

### ISSUE THREAD

**Issue by nick-l-o3de** [o3de/tsc#130]

**Comment by thefranke** [comment]
Need Maintainer rights for Joerg Mueller

**Comment by nick-l-o3de** [comment]
It is up to the SIG-chairs to walk new maintainers / contributors thru the process.  The TSC doesn't actually have a say or decision making in whether someone gets maintainer rights.  SIG-Chairs are more in-tune with the kind and quality of contributions of a contributor and better able to pick apart security issues / viability.
