### ISSUE TITLE
TSC Agenda - July 02 2024

### ISSUE THREAD

**Issue by nick-l-o3de** [o3de/tsc#131]
Add any agenda items here.

**Comment by Ulrick28** [comment]
Would like to discuss the below release schedule:

Feature lock: Monday Aug 5th, 2024 (After Siggraph). No new features allowed into stabilization unless granted an exception. Bug Fixes are allowed.
Full Code lock: Tuesday Sept 25th, 2024. No PR's allowed into stabilization unless granted an exception
Prerelease dry run: Monday Oct 7th, 2024
Release: Wednesday Oct 9th, 2024

**Comment by Naomi-Wash** [comment]
1. Discord cleanup status
2. GitHub Maintainer cleanup
