### ISSUE TITLE
Request to publish SIG Issue Triage Guide

### ISSUE THREAD

**Issue by forhalle** [o3de/tsc#15]
I'd like to publish the below SIG Issue Triage Guide, which outlines and standardizes the process SIGs should use to triage GitHub issues into their backlogs. This guide was initially published internally at Amazon with an open source perspective, and all SIGs are currently following the process outlined. I'd like to move this guide to an accessible location for all contributors to follow.

[SIG Issue Triage Guide.pdf](https://github.com/o3de/tsc/files/8084636/SIG.Issue.Triage.Guide.pdf)

**Comment by lmbr-pip** [comment]
This feels like something that should be part of the [community repro](https://github.com/o3de/community). All other SIGs can then reference it as required.

As there was no public guide, we ended up writing our own. See:
* https://github.com/o3de/sig-network/blob/main/TRIAGE_GUIDE.md
* https://github.com/o3de/sig-content/blob/main/TRIAGE_GUIDE.md 
etc.

Would be good to get these aligned with the common guide.

**Comment by forhalle** [comment]
Next Steps
* Community repo is the appropriate location
* We should standardize label usage across all sigs
* @forhalle will create a PR and have it submitted to the tsc mailing list (work with ninepoints)

**Comment by forhalle** [comment]
@lmbr-pip submitted a PR to publish the guide to o3de/community: https://github.com/o3de/community/pull/146#pullrequestreview-1095354941

He will message the SIGs to advertise the guide, and will close this issue.

**Comment by lmbr-pip** [comment]
Delivered to community repro, this can be closed out.
