### ISSUE TITLE
TSC Co-Chair Nominations Ongoing (ends 2022-06-10)

### ISSUE THREAD

**Issue by jeremyong-az** [o3de/tsc#33]
## Co-chair Role

The TSC currently does not have an assigned co-chair, who once elected, would have the following responsibilities:

- Assumes chairperson role if the chairperson abdicates or is absent
- Assists in the oversight of the Technical Steering Committee described in [this charter](https://github.com/o3de/tsc)

## Nomination

Community members and partners may nominate themselves or other individuals. In either case, the nomination, once accepted, should ideally be accompanied by:

- An introduction including name, Discord username, and background
- Acknowledgement of the role and responsibilities
- A statement about the individual's goals with respect to the project and/or community

## Nomination requirements

All nominees must be current members of the TSC.

## Election

The election period will begin the week following the nomination period (starting June 30 2022) and the vote will be held among members of the TSC subject to existing rules regarding voting quorum.

**Comment by RoddieKieley** [comment]
I, Roddie Kieley, would be willing to take on the responsibility of executing the duties of Co-Chair of the TSC of the O3DF.

You can find me on Discord as RoddieKieley[RedHat] and as my name implies I currently work with Red Hat, the enterprise software company with an open source development model, where our mission is "to be the catalyst in communities of customers, contributors, and partners creating better technology the open source way".

I have been at Red Hat for about 6.5 years and am a co-founder of the Gaming Community of Practice whose more specific mission is to help make the Game Industry relevant to Red Hat and Red Hat relevant to the Game Industry. 

As a part of those missions I advised on the decision for Red Hat to become a founding member of the O3DF, helped with the inception and launch of arcade.redhat.com, and was the leader of the development team behind Pod Escape there. 

By 'day job' I am the Principal Software Engineer fulfilling the role of 'AMQ on OpenShift Lead', am a committer and Project Management Committee member at Apache Qpid, and have maintained the MacPorts Qpid Proton C messaging client distribution.

I stepped into the TSC as Red Hat's representative at the end of March this year, while continuing to serve as the initial co-chair of the platform sig.

Working backward over the past 24 years, prior relevant background includes:
- Technical Director at Other Ocean Ltd. with varying credits in Rad Boarding, #IDARB, and the USF IV PS4 port.
- Founder of Binary Dawn Interactive, a mobile game startup that produced and released Through To Iota, WordUs2, and Giggle Water apps.
- Was at Sir-Tech Canada Ltd. to develop Jagged Alliance 3, which wasn't to be, and instead earned credit on Wizardry 8.
- B.Sc. in CS focusing on graphics, animation, and ai/neural networks
- Co-developed edutainment title 'Backpack Adventures in Asthma' for John Hopkins University

If given the opportunity to execute the role of Co-Chair of the TSC for the O3DF my foremost goal is to ensure consistent stewardship and function of the committee itself in partnership with the other members and sigs. 

Further to that it is to make decisions based on technical and community merit, as best as it can be defined, for the betterment of the project and sub-projects related to the engine and foundation.

**Comment by jeremyong-az** [comment]
Thanks @RoddieKieley ! I'm happy to second your nomination.
