### ISSUE TITLE
Clarification on process to add projects to o3de-extras (For Loft Scene Robot Sample)

### ISSUE THREAD

**Issue by spham-amzn** [o3de/tsc#60]
Now that we the o3de/o3de-extras repo for gems and projects, is there a guide or approval process that has been established to add projects to https://github.com/o3de/o3de-extras/tree/development/Projects ?  

We have a sample project developed jointly with another org currently located at https://github.com/RobotecAI/o3de-demo-project 

This project is dependent on two gems that are outside of o3de:
* **Archviz** ( https://github.com/o3de/loft-arch-vis-sample/tree/main/Gems/ArchVis )
  This gem resides inside the loft-scene sample repository, but can be used in other projects
* **ROS2** (https://github.com/RobotecAI/o3de-ros2-gem)
  This gem is in the process of being moved to the o3de/o3de-extras repo

The sample project (as well as the ROS2 gem) is going through the process of being transferred to the sig-simulation group for ownership going forward. It will also go through the process of review to bring the code base up to O3DE coding standards.

The proposed final location for this sample project:

```https://github.com/o3de/o3de-extras/tree/development/Projects/RobotVacuumSample```

**Comment by jeremyong-az** [comment]
There isn't an approval process that I'm aware of. The extras repo serves as a location where any SIG can deposit code that they deem is unlikely to be useful to the broad majority of O3DE users, so the SIG ultimately has the say here. The only reason I can think of where approval may be needed is if the code skews heavily towards a particular corporate interest (just like any other corporate code or code that relies on a proprietary license or interacts with closed-source services). I'll leave this issue up though for others to see and potentially dissent.

**Comment by spham-amzn** [comment]
Thank you for the clarification
