### ISSUE TITLE
TSC Chair and Co-Chair Elections (to close 2023-01-03)

### ISSUE THREAD

**Issue by jeremyong-az** [o3de/tsc#62]
What: As per the [charter](https://github.com/o3de/tsc/blob/main/README.md), the initial eighteen month period immediately following the project's inception will elapse in January 2023. As such, new elections are needed to determine TSC leadership in the coming period.

Who: Only TSC members are eligible for participation in both the nomination and voting process.

How: After nominations, which may extend till the voting deadline, a 2/3rds vote is needed to secure the position of either chair or co-chair.

Read more about TSC membership proceedings [here](https://github.com/o3de/tsc/blob/main/README.md#tsc-membership).

In addition, I will be leaving Amazon at the start of 2023, and as part of that departure, will abdicate my position as the TSC chair and membership. I am committed to assisting in the transition up till that time, and am grateful for the opportunity to work with and support the O3DE project.

**Comment by kberg-amzn** [comment]
I nominate Nick Lawson for TSC chair and Tobias for co-chair.

**Comment by thefranke** [comment]
I'd second the vote for Nick, and I accept the nomination for co-chair

**Comment by RoddieKieley** [comment]
Having worked with both Nick and Tobias in 2022 I have no hesitation in voting for Nick as chair and Tobias as co-chair. I think the TSC would be in good hands with Nick's experience and focus on balanced community contribution and Tobias's focus on seeing the project move forward.

**Comment by lawsonamzn** [comment]
I'd prefer if more non-AMZN folks got involved (just in general, across the entire project) but if nobody steps up, I can do it.

**Comment by RoddieKieley** [comment]
As the original post occurred during a time when many were out for the holidays and likely less connected than usual, it was decided during this week's meeting that a further opportunity to contribute to the election process should be opened.

As such please consider this thread open and either place your vote here or via the TSC mailing list.
This continued opportunity to vote will cease at 12:01am North American Eastern Time, Tuesday, January 17th.

**Comment by RoddieKieley** [comment]
At today's meeting this was concluded with it becoming it official that Nick Lawson is chair and Tobias Franke is co-chair for 2023. Thanks to everyone who participated!
