### ISSUE TITLE
TAC/TSC Monthly Sig Meeting 1/2023

### ISSUE THREAD

**Issue by byrcolin** [o3de/tsc#64]
All SIG's please leave a comment on your SIG's roadmap for reading in the next meeting.

**Comment by lawsonamzn** [comment]
Consider linking the comment, roadmap item, issue or other over here.

**Comment by lmbr-pip** [comment]
As SIG/Network chair I will miss this meeting. Hopefully SIG/Network co-chair can make it:


For SIG/Network 

* We just delivered Client/server split work which adds build time separation of client/server logic and will be used to drive down server build sizes. See https://github.com/o3de/sig-network/blob/main/rfcs/rfc-net-20221020-1-clientserver.md
* We are working on a big refresh for the o3de-multiplayer sample project
* We are holding elections for new chair(s) and expect to have new chair(s) in place early feb.

Our roadmap is here https://github.com/orgs/o3de/projects/22 (but like many roadmaps its currently private and we need to find who has the permissions to flip to public)

**Comment by Kadino** [comment]
[SIG-Testing roadmap](https://github.com/orgs/o3de/projects/35/views/1)
I cannot make the current meeting time, perhaps co-chair @AMZN-Dk can attend?

**Comment by amzn-changml** [comment]
Here's the [SIG-Build roadmap](https://github.com/orgs/o3de/projects/39/views/1). @dshmz and I are planning on attending.

Some notable items to discuss:
- Alternative AR infrastructure and workflows (as in: hosting CI/CD on other systems)
- 3rd Party package contribution workflows
- Static code analysis in collaboration with SIG-Testing
- Packaging on OS specific marketplaces

**Comment by hultonha** [comment]
Here is [sig-simulation's roadmap](https://github.com/orgs/o3de/projects/23) - still WIP but more issues will be added soon. It's relatively up to date in terms of things that have been completed and are in progress (tagging @lgleim and @epsilon-delta for visibility - co-chairs of sig-simulation).

**Comment by lumberyard-employee-dm** [comment]
Here is the link to the WIP [SIG-Core roadmap](https://github.com/orgs/o3de/projects/31)

**Comment by byrcolin** [comment]
SIG-Platforms: [https://github.com/orgs/o3de/projects/20](roadmap)
ARM64 support is ongoing
Bug fixes

**Comment by OBWANDO** [comment]
As we have more people starting to come over from cross-pollination and awareness some are unsure why and where to get into SIGs. It may be helpful if the SIG readme could answer a few of these questions where they can be found.

How can people get involved in each area?
Where would they start? 
Why is it important for them to become a part of your SIG?
Who would be interested in joining.

**Comment by chanmosq** [comment]
SIG Docs and Community
- We are working on creating roadmap items and establishing that process. The roadmap can be found here https://github.com/orgs/o3de/projects/15
- We are cleaning the backlog for o3de.org - setting priorities and organizing for our own tracking of issues that folks from sig-docs-community can work on
- Continuing to resolve gaps in docs - includes EBus, Memory, Networking, Script Canvas.

**Comment by greerdv** [comment]
I'd like to discuss the good first issue label.

If you click on this link

![image](https://user-images.githubusercontent.com/82226198/215074311-992e2a7a-ac11-4722-ae78-837adc404304.png)

it takes you to a query based on the label "good first issue". However we are using the label "good-first-issue" (with hyphens) and so that link returns no results, even though we have dozens of issues we have labelled. This is obviously problematic for attracting new community participants.

**Comment by thefranke** [comment]
This is the [sig-graphics-audio roadmap](https://github.com/orgs/o3de/projects/41)

I'd like to discuss the following items:
* [Cross cutting issue with sig-build](https://github.com/o3de/o3de/pull/12009) on Windows update
* sig-uiux: Is there a plan to eventually move to QT6?
* Getting calendar entries for wg-mobile
