### ISSUE TITLE
TSC Meeting Agenda - March 07, 2023

### ISSUE THREAD

**Issue by lawsonamzn** [o3de/tsc#71]
This is the TSC agenda for March 07, 2023

Add items by commenting on this issue.

**Comment by lawsonamzn** [comment]
Discuss minimum version of windows required (for raytracing shader stuff)

**Comment by thefranke** [comment]
From @lawsonamzn comment -> https://github.com/o3de/o3de/pull/12009

In addition, I'd like to bring up a report on the first `wg-mobile` gathering we had.

We would like to:
- Get a mobile label
- Set up a calendar event (once we reached first agreement on a fixed meeting date)

**Comment by lawsonamzn** [comment]
Note archived 
https://github.com/o3de/tsc/blob/main/meetings/notes/tsc-meeting-20230307.md
