### ISSUE TITLE
TSC Meeting Agenda - 3/14/2023

### ISSUE THREAD

**Issue by lawsonamzn** [o3de/tsc#72]
Please leave agenda items here if you would like the TSC to discuss

**Comment by smurly** [comment]
Please consider adding github issue label `platform/linux/arm64` in advance of work for this platform to distinguish arm64 specific issues from other linux issues.
for reference https://github.com/o3de/sig-platform/blob/main/rfcs/linux-arm64-support.md

**Comment by lawsonamzn** [comment]
from the channel:
> thoraxe (Erik Jacobs) [Red Hat] — Yesterday at 12:19 PM
> https://github.com/search?q=topic%3Agamedev+org%3Ao3de&type=Repositories
> This is a link to all repos tagged with topic gamedev within the O3DE org.
> Would it be possible to add the tag sample or example to all the demo repos (eg: 
> https://github.com/o3de/NewspaperDeliveryGame) so that we can easily link to all of the sample/examples in the org?

**Comment by lawsonamzn** [comment]
https://github.com/o3de/tsc/blob/main/meetings/notes/tsc-meeting-20230314.md
