### ISSUE TITLE
All-Sigs roadmap / status meeting for 3/28/2023

### ISSUE THREAD

**Issue by lawsonamzn** [o3de/tsc#74]
8AM Pacfic Time (US) in the TSC/TAC discord channel, will be the monthly "all sigs" status update and roadmap.

See the previous agenda for an example:
https://github.com/o3de/tsc/issues/70

Please attach links to the SIG roadmap (And anything to notify teams of in case of your absence, it will be read for you), in comments below.

**Comment by chanmosq** [comment]
SIG-Docs-Community Roadmap: https://github.com/orgs/o3de/projects/15/

SIG Updates:
- Created a docs stabilization branch for O3DE 23.05 release
- Documented the [docs release process](https://github.com/o3de/sig-release/blob/main/releases/Process/Docs%20Release%20Process.md)
- Added [SIG roadmaps](https://deploy-preview-2322--o3deorg.netlify.app/docs/contributing/roadmaps/) to the contributing guide
- Improving the output Doxygen-generated API Reference
  - Documenting the process and publishing the tool
- Continued maintenance and authoring of various topics in the O3DE Documentation

**Comment by tonybalandiuk** [comment]
SIG-Release Roadmap https://github.com/orgs/o3de/projects/29

Issue to discuss with TSC:
1. Last month sig-release decided o3de-extras was a canonical repo, which means we will start including it in the next release 23.05 stabilization process, and could hold the release if blocking issues are found. Want to discuss this with the TSC. Additional details of the repo were recently brought to our attention (a) o3de-extras contains gems from external 3rd parties and we cannot guarantee that any of these will be compatible with the release.  (b) we have no guarantee that the repository is being tested/exercised during release stabilization so we may not discover bugs that may exist in the repo - this introduces risk into the release. We would like the TSC's opinion of where o3de-extras lands with respect to "O3DE the project" and how they think of O3DE extras. Should O3DE extras be part of release stabilization.

What we did last month
1. Stabilization branch was created. The stabilization period ends on April 11th, 2023 PDT. Next milestone: Code freeze on major bugs, Versioned API reference generation, and release notes finalized by the docs team.
2. SIG Docs community created the PR to make all SIG roadmaps more discoverable by creating a new roadmaps page and updating the contribute home page: https://discord.com/channels/805939474655346758/821692567355523152/1087850071816683570
3. Proposed to TSC on adding "Maintaining roadmap" responsibility on each SIG charter. Waiting for the response.

What we're going next month based on the roadmap: https://github.com/orgs/o3de/projects/29
1. Release considered stable to go live on May 3rd, 2023.
2. Complete all action items on [RFC "Maintaining Roadmap"](https://github.com/o3de/sig-release/issues/128).
3. Completes the [O3DE release process](https://github.com/o3de/sig-release/issues/134).

**Comment by uoduckswtd1** [comment]
Topics from Marketing/Advocacy Committee:

1. To help onboard users, we're focused on creating "how to" tutorials. Our ask: for the TSC and SIGs to help us identify the top technically-rich O3DCon presentations in each of the different areas that the SIGs focus on, for the purpose of using them as the basis for the "how to" tutorials.

O3DCon presentations on O3DE YouTube: https://www.youtube.com/playlist?list=PLCQwFpnHSZQgzCpMmbxruFkWr3d73ZfEJ

2. To help onboard contributors, we'd like to propose hosting livestream webinars to enable each SIG to communicate more broadly the SIG's focus, roadmap, good first issues, places to dive in, etc. The livestreams will be recorded and added to O3DE YouTube following the livestream.

3. We're starting to draft a plan for a mentorship program and would like to understand the needs of each SIG in terms of help needed. This data will be used to shape the creation of O3DE's mentorship program.

**Comment by lawsonamzn** [comment]
"I'll add an issue, but in today's TSC meeting Tony and I would like to discuss the extras repo and the use of canonical terminology, and how that might create some false expectations." Joe Bryant

**Comment by lmbr-pip** [comment]
SIG-Network Roadmap

SIG Updates
* Soft launched the new MultiplayerSample: https://github.com/o3de/o3de-multiplayersample and all the assets https://github.com/o3de/o3de-multiplayersample-assets - Major new multiplayer sample - 3rd person laser shooter

**Comment by lmbr-pip** [comment]
SIG-Security (No items on roadmap
* Reviewing security issues for the release and trying to get issues patched or ETAs for fixing from SIG.
