### ISSUE TITLE
TSC meeting agenda for Tuesday, April 11 2023

### ISSUE THREAD

**Issue by lawsonamzn** [o3de/tsc#76]
Please leave any agenda items here that you'd like to discuss in the TSC.  The meeting will be at 8am PST in the TAC/TSC voice channel in the discord.

The meeting is also office hours, so anyone can show up with questions for the TSC.

**Comment by aFinchy** [comment]
- SIG Docs & Community Election yield replacements for the current chairs.
- SIG Operations Election yield replacements for the current chairs.

What to do in this scenario.
