### ISSUE TITLE
All-Sigs Roadmap Meeting for April 25 2023

### ISSUE THREAD

**Issue by lawsonamzn** [o3de/tsc#78]
8AM Pacfic Time (US) in the TSC/TAC discord channel, will be the monthly "all sigs" status update and roadmap on 4/25/2023.

See the previous agenda for an example:
https://github.com/o3de/tsc/issues/74

Please attach links to the SIG roadmap (And anything to notify teams of in case of your absence, it will be read for you), in comments below.

**Comment by lmbr-pip** [comment]
SIG-Network Roadmap: https://github.com/orgs/o3de/projects/22

* [MultiplayerSample](https://github.com/o3de/o3de-multiplayersample/tree/stabilization/2305) is complete for the 2305 release. No further work planned. Team ran several play tests hosting about 40+ games with 5-10 players per game. Feedback on sample is very positive ... "surprisingly fun".
      * Added music, splashscreens, dialed up the environmental chaos and added jump pads. 
      * Blog and launch materials are prepared.

https://user-images.githubusercontent.com/61438964/233748467-7a1db8a7-46bb-42b8-ab25-7235d766fa63.mp4




SIG-Security Roadmap (No Items)
* SIG needs to hold elections as both chairs need to step away. 
* TSC may want to evaluate SIG as it has very low engagement and limited capacity. Hopefully new Chair(s) can reinvigorate SIG.

**Comment by lumberyard-employee-dm** [comment]
SIG-Core Roadmap: https://github.com/orgs/o3de/projects/31
* The RFCs for the Archive System Replacement of CryPak have been published for public review under issue: https://github.com/orgs/o3de/projects/31/views/1?pane=issue&itemId=26253919
* The list of SIG-Core RFCs are now available for examination in the [rfcs](https://github.com/o3de/sig-core/tree/streaming-archive-document/rfcs) directory of the sig-core repo
* SIG-Core is still looking for interested volunteers for as a co-chair for governance.

**Comment by tonybalandiuk** [comment]
SIG-Release Roadmap https://github.com/orgs/o3de/projects/29


What we did last month

* Managed exceptions entering stabilization

* Updated stabilization process to include updating release notes

* Decided to move forward with this release without a single designated release manager. Release duties are being shared across sig chair, co-chair, and PM from LF.
* Release scheduled to go live on May 3rd, 2023. Dry run on 4/27
* we will then update release documentation to reflect any lessons learned from the release.
