### ISSUE TITLE
Agenda for 6/13/2023

### ISSUE THREAD

**Issue by nick-l-o3de** [o3de/tsc#82]
Agenda for 13th of June 2023

Add items as appropriate!

**Comment by tonybalandiuk** [comment]
SIG-Release will use this TSC meeting to continue the retrospective for 23.05 Release. Feedback on the release is here:
https://docs.google.com/spreadsheets/u/2/d/1jvPxKBBQTSfkS3jg570jZ9snFaQUUyAtUQu9SBwC1Xc/edit#gid=0

In this TSC meeting SIG-Release chair @tonybalandiuk and co-chair @vincent6767 will guide the discussion. We will:
1) Review each piece of feedback
2) discuss with attendees
3) determine next steps

**Comment by tonybalandiuk** [comment]
As discussed today, I realized that we didn't promote this retro at all, so let's do the retro on 6/20 instead. I have posted in SIG-All and SIG-Release to notify community members.
