### ISSUE TITLE
All-sigs and roadmap meeting for july 25th, 2023.

### ISSUE THREAD

**Issue by nick-l-o3de** [o3de/tsc#89]
If you have any interesting roadmap items or updates, or messages for other sigs, please add them to this agenda.

**Comment by nick-l-o3de** [comment]
https://github.com/o3de/tsc/issues/89

**Comment by lumberyard-employee-dm** [comment]
SIG-Core Updates:
Build fixes were added to support the newest [GCC 13/Clang 14](https://github.com/o3de/o3de/pull/16257) Compilers
Project Export Scripts for both [Engine-centric](https://github.com/o3de/o3de/pull/16285) and [Project-centric](https://github.com/o3de/o3de/pull/16406) workflows have been introduced.

SIG-Core Roadmap: https://github.com/orgs/o3de/projects/31

**Comment by rainbj** [comment]
- Announcement of the Rev the engine results. Document - https://docs.google.com/document/d/1J6uzkGa9_g3a8AFuN4XnfHeS_uluAPnSMsrCjjbNOS4/edit

**Comment by Naomi-Wash** [comment]
Link to the meeting recording: https://drive.google.com/file/d/15tU4yJVFssn60lYwKT2dyQHxHw8QMWzz/view?usp=drive_link
