### ISSUE TITLE
All sigs roadmap and discussion meeting for August 29, 2023

### ISSUE THREAD

**Issue by nick-l-o3de** [o3de/tsc#93]
It is recommended for all sig chair/cochair to touch base during this meeting regarding roadmap items, as well as any other issues that other sigs should be aware of.

Sigs, please add your roadmap links or items below.

If you are unable to attend, you can still reply to this with a message for all the other sigs and they will be read out during the meeting for you.

**Comment by lumberyard-employee-dm** [comment]
SIG-Core Update: We have two new RFCs that have been published.

* https://github.com/o3de/sig-core/issues/57
The oldest proposal is for adding support of a Quality Scalability framework that is built on top of the Console Command and Settings Registry system, to allow association of "quality" levels with specific platforms and devices.
Developers would be able to detect device characteristics and run rule based logic based on those characteristics to set a specific quality level or console variable value.
The primary use case is for Mobile graphics related settings based on which kind of device is being used

* https://github.com/o3de/sig-core/issues/58
The latest RFC details a mechanism for creating a script-only O3DE project, which would be able to launch the Editor without needing to download any 3rdParty libraries or compiling any code. An SDK engine layout is the main use case for the feature and would allow the user to get into the Editor in a lower time frame.

**Comment by Naomi-Wash** [comment]
Here is the meeting recording. https://drive.google.com/file/d/15gpSEzm3Q5DwPXcCXh5ITvmhfyLlWkeM/view?usp=drive_link
